version: "3"
services:

  mongo1:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-1:/data/db
      - mongo-config-1:/data/configdb
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 1
  mongo2:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-2:/data/db
      - mongo-config-2:/data/configdb
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 2

  mongo3:
    image: mongo:3.4
    command: mongod --smallfiles --replSet rs1 --noauth --oplogSize 3
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - mongo-data-3:/data/db
      - mongo-config-3:/data/configdb
    networks:
      - mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo.replica == 3

networks:
  mongo:

volumes:
  mongo-data-1:
  mongo-data-2:
  mongo-data-3:
  mongo-config-1:
  mongo-config-2:
  mongo-config-3: