version: "2"
services:

  mongors1n1:
    container_name: mongors1n1
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors1n1:/data/db

  mongors1n2:
    container_name: mongors1n2
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors1n2:/data/db

  mongors1n3:
    container_name: mongors1n3
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors1 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors1n3:/data/db

  mongors2n1:
    container_name: mongors2n1
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors2n1:/data/db

  mongors2n2:
    container_name: mongors2n2
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors2n2:/data/db

  mongors2n3:
    container_name: mongors2n3
    image: mongo:3.4
    command: mongod --smallfiles --replSet mongors2 --dbpath /data/db --nojournal --oplogSize 16 --noauth --shardsvr
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongors2n3:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo:3.4
    command: mongod --smallfiles --replSet csReplSet --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongocfg1:/data/db

  mongocfg2:
    container_name: mongocfg2
    image: mongo:3.4
    command: mongod --smallfiles --replSet csReplSet --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongocfg2:/data/db

  mongocfg3:
    container_name: mongocfg3
    image: mongo:3.4
    command: mongod --smallfiles --replSet csReplSet --dbpath /data/db --configsvr --noauth --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mongocfg3:/data/db

  mongos1:
    container_name: mongos1
    image: mongo:3.4
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb csReplSet/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
    ports:
      - 27017:27017

  mongos2:
    container_name: mongos2
    image: mongo:3.4
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb csReplSet/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017
    ports:
      - 27018:27017

